### ISSUE TITLE
move handler directory up one level

### ISSUE THREAD

**Issue by ben-tinc** [arbox/chatbot2#16]

**Comment by ben-tinc** [comment]
commit exists at ben-tinc/chatbot2@a8e5d16edf1fe96d294f68cba83ebe8b995b8d5e
I am still a bit unsure if I did this correctly though.

**Comment by arbox** [comment]
That looks good! Any corrections before I merge?

**Comment by ben-tinc** [comment]
I still need to adapt the description in the docs to reflect the change.

**Comment by arbox** [comment]
Ok, ping me as far as you are ready.

**Comment by ben-tinc** [comment]
@arbox Pull request #17 fixes this and also #8
